/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface YieldSyncV1VaultRecordInterface extends utils.Interface {
  functions: {
    "addAdmin(address,address)": FunctionFragment;
    "addMember(address,address)": FunctionFragment;
    "admin_yieldSyncV1Vaults(address)": FunctionFragment;
    "member_yieldSyncV1Vaults(address)": FunctionFragment;
    "participant_yieldSyncV1Vault_access(address,address)": FunctionFragment;
    "removeAdmin(address,address)": FunctionFragment;
    "removeMember(address,address)": FunctionFragment;
    "yieldSyncV1Vault_admins(address)": FunctionFragment;
    "yieldSyncV1Vault_members(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAdmin"
      | "addMember"
      | "admin_yieldSyncV1Vaults"
      | "member_yieldSyncV1Vaults"
      | "participant_yieldSyncV1Vault_access"
      | "removeAdmin"
      | "removeMember"
      | "yieldSyncV1Vault_admins"
      | "yieldSyncV1Vault_members"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addMember",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "admin_yieldSyncV1Vaults",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "member_yieldSyncV1Vaults",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "participant_yieldSyncV1Vault_access",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldSyncV1Vault_admins",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldSyncV1Vault_members",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "admin_yieldSyncV1Vaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "member_yieldSyncV1Vaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participant_yieldSyncV1Vault_access",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldSyncV1Vault_admins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldSyncV1Vault_members",
    data: BytesLike
  ): Result;

  events: {};
}

export interface YieldSyncV1VaultRecord extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: YieldSyncV1VaultRecordInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admin_yieldSyncV1Vaults(
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    member_yieldSyncV1Vaults(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    participant_yieldSyncV1Vault_access(
      participant: PromiseOrValue<string>,
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean] & { admin: boolean; member: boolean }>;

    removeAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    yieldSyncV1Vault_admins(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    yieldSyncV1Vault_members(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  addAdmin(
    _yieldSyncV1Vault: PromiseOrValue<string>,
    admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addMember(
    _yieldSyncV1Vault: PromiseOrValue<string>,
    member: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admin_yieldSyncV1Vaults(
    admin: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  member_yieldSyncV1Vaults(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  participant_yieldSyncV1Vault_access(
    participant: PromiseOrValue<string>,
    yieldSyncV1Vault: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean] & { admin: boolean; member: boolean }>;

  removeAdmin(
    _yieldSyncV1Vault: PromiseOrValue<string>,
    admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeMember(
    _yieldSyncV1Vault: PromiseOrValue<string>,
    member: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  yieldSyncV1Vault_admins(
    yieldSyncV1Vault: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  yieldSyncV1Vault_members(
    yieldSyncV1Vault: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  callStatic: {
    addAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    admin_yieldSyncV1Vaults(
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    member_yieldSyncV1Vaults(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    participant_yieldSyncV1Vault_access(
      participant: PromiseOrValue<string>,
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean] & { admin: boolean; member: boolean }>;

    removeAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    yieldSyncV1Vault_admins(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    yieldSyncV1Vault_members(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    addAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admin_yieldSyncV1Vaults(
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    member_yieldSyncV1Vaults(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    participant_yieldSyncV1Vault_access(
      participant: PromiseOrValue<string>,
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    yieldSyncV1Vault_admins(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    yieldSyncV1Vault_members(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admin_yieldSyncV1Vaults(
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    member_yieldSyncV1Vaults(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participant_yieldSyncV1Vault_access(
      participant: PromiseOrValue<string>,
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAdmin(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeMember(
      _yieldSyncV1Vault: PromiseOrValue<string>,
      member: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    yieldSyncV1Vault_admins(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yieldSyncV1Vault_members(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
