/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type MessageHashDataStruct = {
  signature: PromiseOrValue<BytesLike>;
  signer: PromiseOrValue<string>;
  signedMembers: PromiseOrValue<string>[];
  signatureCount: PromiseOrValue<BigNumberish>;
};

export type MessageHashDataStructOutput = [
  string,
  string,
  string[],
  BigNumber
] & {
  signature: string;
  signer: string;
  signedMembers: string[];
  signatureCount: BigNumber;
};

export interface ISignatureManagerInterface extends utils.Interface {
  functions: {
    "signMessageHash(address,bytes32,bytes)": FunctionFragment;
    "updatePause(bool)": FunctionFragment;
    "vaultMessageHashData(address,bytes32)": FunctionFragment;
    "vaultMessageHashes(address)": FunctionFragment;
    "yieldSyncGovernance()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "signMessageHash"
      | "updatePause"
      | "vaultMessageHashData"
      | "vaultMessageHashes"
      | "yieldSyncGovernance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "signMessageHash",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultMessageHashData",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultMessageHashes",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldSyncGovernance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "signMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultMessageHashData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultMessageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldSyncGovernance",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISignatureManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISignatureManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    signMessageHash(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vaultMessageHashData(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[MessageHashDataStructOutput]>;

    vaultMessageHashes(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<[string]>;
  };

  signMessageHash(
    yieldSyncV1Vault: PromiseOrValue<string>,
    messageHash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePause(
    pause: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vaultMessageHashData(
    yieldSyncV1Vault: PromiseOrValue<string>,
    messageHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<MessageHashDataStructOutput>;

  vaultMessageHashes(
    yieldSyncV1Vault: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  yieldSyncGovernance(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    signMessageHash(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultMessageHashData(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<MessageHashDataStructOutput>;

    vaultMessageHashes(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    signMessageHash(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vaultMessageHashData(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vaultMessageHashes(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    signMessageHash(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vaultMessageHashData(
      yieldSyncV1Vault: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultMessageHashes(
      yieldSyncV1Vault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yieldSyncGovernance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
