/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockDappSol from "./MockDapp.sol";
export type { mockDappSol };
export type { MockAdmin } from "./MockAdmin";
export type { MockERC20 } from "./MockERC20";
export type { MockERC721 } from "./MockERC721";
export type { MockSignatureManager } from "./MockSignatureManager";
export type { MockYieldSyncGovernance } from "./MockYieldSyncGovernance";
