/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type MessageHashDataStruct = {
  signature: PromiseOrValue<BytesLike>;
  signer: PromiseOrValue<string>;
  signedMembers: PromiseOrValue<string>[];
  signatureCount: PromiseOrValue<BigNumberish>;
};

export type MessageHashDataStructOutput = [
  string,
  string,
  string[],
  BigNumber
] & {
  signature: string;
  signer: string;
  signedMembers: string[];
  signatureCount: BigNumber;
};

export interface MockSignatureManagerInterface extends utils.Interface {
  functions: {
    "ERC1271_MAGIC_VALUE()": FunctionFragment;
    "isValidSignature(bytes32,bytes)": FunctionFragment;
    "paused()": FunctionFragment;
    "signMessageHash(address,bytes32,bytes)": FunctionFragment;
    "updatePause(bool)": FunctionFragment;
    "vaultMessageHashData(address,bytes32)": FunctionFragment;
    "vaultMessageHashes(address)": FunctionFragment;
    "yieldSyncGovernance()": FunctionFragment;
    "yieldSyncV1VaultRecord()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ERC1271_MAGIC_VALUE"
      | "isValidSignature"
      | "paused"
      | "signMessageHash"
      | "updatePause"
      | "vaultMessageHashData"
      | "vaultMessageHashes"
      | "yieldSyncGovernance"
      | "yieldSyncV1VaultRecord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ERC1271_MAGIC_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "signMessageHash",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultMessageHashData",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultMessageHashes",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldSyncGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldSyncV1VaultRecord",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC1271_MAGIC_VALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultMessageHashData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultMessageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldSyncGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldSyncV1VaultRecord",
    data: BytesLike
  ): Result;

  events: {
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface MockSignatureManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockSignatureManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ERC1271_MAGIC_VALUE(overrides?: CallOverrides): Promise<[string]>;

    isValidSignature(
      _messageHash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { magicValue: string }>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    signMessageHash(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vaultMessageHashData(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[MessageHashDataStructOutput]>;

    vaultMessageHashes(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<[string]>;

    yieldSyncV1VaultRecord(overrides?: CallOverrides): Promise<[string]>;
  };

  ERC1271_MAGIC_VALUE(overrides?: CallOverrides): Promise<string>;

  isValidSignature(
    _messageHash: PromiseOrValue<BytesLike>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  signMessageHash(
    yieldSyncV1VaultAddress: PromiseOrValue<string>,
    messageHash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePause(
    pause: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vaultMessageHashData(
    yieldSyncV1VaultAddress: PromiseOrValue<string>,
    messageHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<MessageHashDataStructOutput>;

  vaultMessageHashes(
    yieldSyncV1VaultAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  yieldSyncGovernance(overrides?: CallOverrides): Promise<string>;

  yieldSyncV1VaultRecord(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ERC1271_MAGIC_VALUE(overrides?: CallOverrides): Promise<string>;

    isValidSignature(
      _messageHash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    signMessageHash(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultMessageHashData(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<MessageHashDataStructOutput>;

    vaultMessageHashes(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<string>;

    yieldSyncV1VaultRecord(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    ERC1271_MAGIC_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    isValidSignature(
      _messageHash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    signMessageHash(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vaultMessageHashData(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vaultMessageHashes(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    yieldSyncGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    yieldSyncV1VaultRecord(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC1271_MAGIC_VALUE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      _messageHash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    signMessageHash(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePause(
      pause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vaultMessageHashData(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      messageHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultMessageHashes(
      yieldSyncV1VaultAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yieldSyncGovernance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yieldSyncV1VaultRecord(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
